export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "Hello Rohan",
  description: "created new website with react js",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require("../../Images/svg-1.svg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};
